[tool]
id = "dev.garado.transit"
label = "Transit"
versionCode = 3
versionName = "0.3.0"
permissions = ["android.permission.INTERNET"]
# change if you run this on the emulator instead of a real LP3!
serverPackage = "com.lightos"
# serverPackage = "com.thelightphone.sdk.emulator"
