[tool]
id = "dev.garado.transit"
label = "Transit"
versionCode = 2
versionName = "0.2.0"
permissions = ["android.permission.INTERNET", "android.permission.READ_LOGS"]
# change if you run this on the emulator instead of a real LP3!
serverPackage = "com.lightos"
# serverPackage = "com.thelightphone.sdk.emulator"
